import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>Welcome to Starwars Page</h1>

				<ul>
					<Link href={"/characters"}>
						<li className={styles.link}>Visit SSG Characters page</li>
					</Link>
					<Link href={"/planets"}>
						<li className={styles.link}>Visit SSR Planets page</li>
					</Link>
					<Link href={"/vehicles"}>
						<li className={styles.link}>Visit static Vehicles page</li>
					</Link>
				</ul>
			</main>
		</div>
	);
};

export default Home;
